platform :ios, '9.0'
swift_version = '3.0.1'
use_frameworks!

target 'Tourist' do
  pod 'GoogleMaps', '2.1.0'
  pod 'GooglePlaces', '2.1.0'
  pod 'GooglePlacePicker', '2.1.0'
  pod 'SwiftGifOrigin'
  target 'TouristTests' do
    inherit! :search_paths
  end

end
